{
 "title": "CrateDB Cluster Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "cloud_clusters_health" } },
   { "name": "namespace", "query": { "query": "crate_ready" } }
  ]
 },
 "panels": [
  {
   "title": "Global Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of CrateDB Nodes (Pods)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{container=\"crate\"})"
    }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(crate_connections{property=\"open\", protocol!=\"transport\"}) by (protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Selects per second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(crate_query_total_count{query=\"Select\"}[5m]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Inserts per second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(crate_query_total_count{query=\"Insert\"}[5m]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"crate\", pod=~\".*$cluster.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container=\"crate\", pod=~\".*$cluster.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File System Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{container=\"crate\", pod=~\".*$cluster.*\"}[5m]) > 0",
     "legendFormat": "{{pod}} {{device}}"
    }
   ]
  },
  {
   "title": "File System Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{container=\"crate\", pod=~\".*$cluster.*\"}[5m])",
     "legendFormat": "{{pod}} {{device}}"
    }
   ]
  },
  { "title": "Query Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Query error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(crate_query_failed_count{namespace=\"$namespace\"}[5m])) by (query)",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Average Query Duration over the last 1 min",
   "type": "graph",
   "description": "The average query duration for a overall queries.",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(crate_query_sum_of_durations_millis{namespace=\"$namespace\"}[5m])) by (query)\n/\nsum(rate(crate_query_total_count{namespace=\"$namespace\"}[5m])) by (query)",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "graph",
   "description": "Queries per second for overall queries.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 34 },
   "yaxes": [
    { "format": "ops", "label": "queries/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(crate_query_total_count{namespace=\"$namespace\"}[5m])) by (query)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}